pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'eduszabolcsfule/streamlit-app'
        REGISTRY = 'dockerhub'
        K8S_DEPLOY_FILE = 'k8s/deployment.yaml'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/eduszabolcsfule/devops_szabolcsfule.git'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl apply -f $K8S_DEPLOY_FILE'
                }
            }
        }
    }
}
